/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as RideRouteImport } from './routes/ride'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RideSummaryRouteImport } from './routes/ride.summary'
import { Route as RideLoadingRouteImport } from './routes/ride.loading'
import { Route as RideConfirmedRouteImport } from './routes/ride.confirmed'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as DeliverySummaryRouteImport } from './routes/delivery.summary'
import { Route as DeliverySenderRouteImport } from './routes/delivery.sender'
import { Route as DeliveryReceiverRouteImport } from './routes/delivery.receiver'
import { Route as DeliveryLoadingRouteImport } from './routes/delivery.loading'
import { Route as DeliveryConfirmedRouteImport } from './routes/delivery.confirmed'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth.complete-profile'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRoute = RideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RideSummaryRoute = RideSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => RideRoute,
} as any)
const RideLoadingRoute = RideLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => RideRoute,
} as any)
const RideConfirmedRoute = RideConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => RideRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverySummaryRoute = DeliverySummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliverySenderRoute = DeliverySenderRouteImport.update({
  id: '/sender',
  path: '/sender',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryReceiverRoute = DeliveryReceiverRouteImport.update({
  id: '/receiver',
  path: '/receiver',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryLoadingRoute = DeliveryLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryConfirmedRoute = DeliveryConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => DeliveryRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/addresses': typeof AddressesRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRouteWithChildren
  '/wallet': typeof WalletRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/delivery/confirmed': typeof DeliveryConfirmedRoute
  '/delivery/loading': typeof DeliveryLoadingRoute
  '/delivery/receiver': typeof DeliveryReceiverRoute
  '/delivery/sender': typeof DeliverySenderRoute
  '/delivery/summary': typeof DeliverySummaryRoute
  '/order/$id': typeof OrderIdRoute
  '/ride/confirmed': typeof RideConfirmedRoute
  '/ride/loading': typeof RideLoadingRoute
  '/ride/summary': typeof RideSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/addresses': typeof AddressesRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRouteWithChildren
  '/wallet': typeof WalletRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/delivery/confirmed': typeof DeliveryConfirmedRoute
  '/delivery/loading': typeof DeliveryLoadingRoute
  '/delivery/receiver': typeof DeliveryReceiverRoute
  '/delivery/sender': typeof DeliverySenderRoute
  '/delivery/summary': typeof DeliverySummaryRoute
  '/order/$id': typeof OrderIdRoute
  '/ride/confirmed': typeof RideConfirmedRoute
  '/ride/loading': typeof RideLoadingRoute
  '/ride/summary': typeof RideSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/addresses': typeof AddressesRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRouteWithChildren
  '/wallet': typeof WalletRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/delivery/confirmed': typeof DeliveryConfirmedRoute
  '/delivery/loading': typeof DeliveryLoadingRoute
  '/delivery/receiver': typeof DeliveryReceiverRoute
  '/delivery/sender': typeof DeliverySenderRoute
  '/delivery/summary': typeof DeliverySummaryRoute
  '/order/$id': typeof OrderIdRoute
  '/ride/confirmed': typeof RideConfirmedRoute
  '/ride/loading': typeof RideLoadingRoute
  '/ride/summary': typeof RideSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/addresses'
    | '/delivery'
    | '/help'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/ride'
    | '/wallet'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/signup'
    | '/delivery/confirmed'
    | '/delivery/loading'
    | '/delivery/receiver'
    | '/delivery/sender'
    | '/delivery/summary'
    | '/order/$id'
    | '/ride/confirmed'
    | '/ride/loading'
    | '/ride/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/addresses'
    | '/delivery'
    | '/help'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/ride'
    | '/wallet'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/signup'
    | '/delivery/confirmed'
    | '/delivery/loading'
    | '/delivery/receiver'
    | '/delivery/sender'
    | '/delivery/summary'
    | '/order/$id'
    | '/ride/confirmed'
    | '/ride/loading'
    | '/ride/summary'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/addresses'
    | '/delivery'
    | '/help'
    | '/home'
    | '/notifications'
    | '/profile'
    | '/ride'
    | '/wallet'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/signup'
    | '/delivery/confirmed'
    | '/delivery/loading'
    | '/delivery/receiver'
    | '/delivery/sender'
    | '/delivery/summary'
    | '/order/$id'
    | '/ride/confirmed'
    | '/ride/loading'
    | '/ride/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AddressesRoute: typeof AddressesRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RideRoute: typeof RideRouteWithChildren
  WalletRoute: typeof WalletRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OrderIdRoute: typeof OrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/summary': {
      id: '/ride/summary'
      path: '/summary'
      fullPath: '/ride/summary'
      preLoaderRoute: typeof RideSummaryRouteImport
      parentRoute: typeof RideRoute
    }
    '/ride/loading': {
      id: '/ride/loading'
      path: '/loading'
      fullPath: '/ride/loading'
      preLoaderRoute: typeof RideLoadingRouteImport
      parentRoute: typeof RideRoute
    }
    '/ride/confirmed': {
      id: '/ride/confirmed'
      path: '/confirmed'
      fullPath: '/ride/confirmed'
      preLoaderRoute: typeof RideConfirmedRouteImport
      parentRoute: typeof RideRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/summary': {
      id: '/delivery/summary'
      path: '/summary'
      fullPath: '/delivery/summary'
      preLoaderRoute: typeof DeliverySummaryRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/sender': {
      id: '/delivery/sender'
      path: '/sender'
      fullPath: '/delivery/sender'
      preLoaderRoute: typeof DeliverySenderRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/receiver': {
      id: '/delivery/receiver'
      path: '/receiver'
      fullPath: '/delivery/receiver'
      preLoaderRoute: typeof DeliveryReceiverRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/loading': {
      id: '/delivery/loading'
      path: '/loading'
      fullPath: '/delivery/loading'
      preLoaderRoute: typeof DeliveryLoadingRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/confirmed': {
      id: '/delivery/confirmed'
      path: '/confirmed'
      fullPath: '/delivery/confirmed'
      preLoaderRoute: typeof DeliveryConfirmedRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeliveryRouteChildren {
  DeliveryConfirmedRoute: typeof DeliveryConfirmedRoute
  DeliveryLoadingRoute: typeof DeliveryLoadingRoute
  DeliveryReceiverRoute: typeof DeliveryReceiverRoute
  DeliverySenderRoute: typeof DeliverySenderRoute
  DeliverySummaryRoute: typeof DeliverySummaryRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryConfirmedRoute: DeliveryConfirmedRoute,
  DeliveryLoadingRoute: DeliveryLoadingRoute,
  DeliveryReceiverRoute: DeliveryReceiverRoute,
  DeliverySenderRoute: DeliverySenderRoute,
  DeliverySummaryRoute: DeliverySummaryRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface RideRouteChildren {
  RideConfirmedRoute: typeof RideConfirmedRoute
  RideLoadingRoute: typeof RideLoadingRoute
  RideSummaryRoute: typeof RideSummaryRoute
}

const RideRouteChildren: RideRouteChildren = {
  RideConfirmedRoute: RideConfirmedRoute,
  RideLoadingRoute: RideLoadingRoute,
  RideSummaryRoute: RideSummaryRoute,
}

const RideRouteWithChildren = RideRoute._addFileChildren(RideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AddressesRoute: AddressesRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RideRoute: RideRouteWithChildren,
  WalletRoute: WalletRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  OrderIdRoute: OrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
